package: tier
version: '2.1.1'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/tier


requires:
    php:
        version: '>8.3,<9'
    redaxo: ^5.17
    packages:
        yform: "^4"
        yform_field: ">=2.5.0"

page:
    title: translate:tier_title
    icon: rex-icon fa-paw
    tier:
    block: system
    prio: 19
    perm: tier[]
    subpages:
        entry:
            title: translate:tier_entry
            icon: rex-icon fa-paw
            perm: tier[]
        category:
            title: translate:tier_category
            icon: rex-icon fa-dragon
            perm: tier[]
        settings:
            title: translate:tier_settings
            icon: rex-icon fa-cogs
            itemClass: pull-right
            perm: admin

default_config:
    editor: 'class="form-control redactor-editor--default"'

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
